name: 'Matomo Main Tests'
description: 'Running Matomo Tests'
inputs:
  test-type:
    description: 'test type'
    required: true
  php-version:
    description: '7.2-8.1'
    required: true
    default: '7.2'
  database-adapter:
    description: 'PDO_MYSQL or MYSQLI'
    required: false
    default: 'PDO_MYSQL'
  node-version:
    description: 'node version default 12'
    required: false
    default: '12'
  secrets:
    description: ''
    required: false

runs:
  using: "composite"
  steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        lfs: false
        submodules: recursive

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ inputs.php-version }}
        extensions:  bcmath, ldap, curl, zip, pdo_mysql, mysqli, gd, redis
        ini-values: |
          memory_limit = 256M,
          max_execution_time=10000,
          always_populate_raw_post_data=-1,
          error_reporting=E_ALL,
          log_errors=on, display_errors=on,
          allow_url_fopen = on,
          zend.exception_ignore_args = Off
          mysqli.allow_local_infile = On
        tools: composer:v2
        coverage: none

    - name: prepare setup
      shell: bash
      run: ./scripts/bash/prepare.sh
      env:
        PHP_VERSION: ${{ inputs.php-version }}
        MATOMO_TEST_TARGET: ${{ inputs.test-type }}
        MYSQL_ADAPTER: ${{ inputs.database-adapter }}

    - name: ${{ inputs.test-type }} Test is running
      shell: bash
      run: |
        ./vendor/phpunit/phpunit/phpunit --configuration ./tests/PHPUnit/phpunit.xml --testsuite ${{ inputs.test-type }}
      env:
        TRAVIS: true
        GITHUB: true
        PHP_VERSION: ${{ inputs.php-version }}
        MYSQL_ADAPTER: ${{ inputs.database-adapter }}
