name: 'Matomo Tests'
description: 'Running Matomo Tests'
inputs:
  test-type:
    type: choice
    description: "test type"
    required: true
    options:
      - UI
      - PHP
      - PluginTests
      - JS
      - Angular
  git-head:
    description: "head"
    required: true
  git-sha:
    description: "sha"
    required: true
  run_id:
    description: "GitHub Run Id"
    required: false
  repository:
    description: "GitHub repository"
    required: false
  run_number:
    description: "GitHub run number"
    required: false
  artifect_pass:
    description: "UI upload passs"
    required: false
  ref:
    description: "Pull request ref"
    required: false
  plugin-name:
    description: "name"
    required: false
  mysql-driver:
    description: "Mysql driver"
    required: false
    options:
      - PDO_MYSQL
      - MYSQLI
  test-command:
    description: "Test name"
    required: false
  php-version:
    description: '7.2-8.1'
    required: true
    default: ''
  node-version:
    description: 'node version default 12'
    required: false
    default: ''
  addition:
    description: 'additional test or setup'
    required: false
    default: ''
  secrets:
    description: ''
    required: false
  php-memory:
    description: "php memory limit"
    required: false
    default: "256M"
  redis-service:
    type: boolen
    description: "require reds services"
    required: false
    default: false
  mysql-service:
    type: boolean
    description: "require mysql services"
    required: false
    default: true

runs:
  using: "composite"
  steps:
    - name: start mysql services
      if: inputs.mysql-service
      shell: bash
      run: |
        docker run --d --name mysql \
            -e ALLOW_EMPTY_PASSWORD=yes \
            -e MYSQL_DATABASE=matomo_tests \
            bitnami/mysql:5.7

    - name: start redis serivces
      if: inputs.redis-service
      shell: bash
      run: |
        docker run --d --name redis -e ALLOW_EMPTY_PASSWORD=yes -p 6379:6379 bitnami/redis:latest
        docker run --d --name redis-sentinel -p 26379:26379 bitnami/redis-sentinel:latest

    - name: Checkout code
      shell: bash
      run: |
        cd /home/runner/work/
        git clone https://github.com/matomo-org/github-action-tests.git appendix

    - name: Checkout code
      if: inputs.tests-type == 'PluginTests'
      uses: actions/checkout@v3
      with:
        repository: matomo-org/matomo
        path: ./matomo

    - name: Move File to right place
      if: inputs.tests-type == 'PluginTests'
      shell: bash
      run: |
        mkdir /home/runner/work/matomo
        mv ./matomo /home/runner/work/matomo/
        ls -l /home/runner/work/appendix

    - name: Checkout Submodule to current Pull request
      if: inputs.tests-type == 'PluginTests'
      shell: bash
      working-directory: /home/runner/work/matomo/matomo
      run: |
        cd plugins/${{ inputs.plugin-name }}
        git submodule update --init -- .
        git fetch origin ${{ inputs.git-head }}
        git checkout ${{ inputs.git-sha }}


      # setup php
    - name: Setup PHP
      if: inputs.php-version != ''
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ inputs.php-version }}
        extensions: bcmath, ldap, curl, zip, pdo_mysql, mysqli, gd, redis, zlib, opcache
        ini-values: |
          post_max_size=256M
          memory_limit=${{ inputs.php-memory}},
          max_execution_time=10000,
          always_populate_raw_post_data=-1,
          error_reporting=E_ALL,
          log_errors=on,
          display_errors=on,
          allow_url_fopen=on,
          zend.exception_ignore_args=Off
          mysqli.allow_local_infile=On
          opcache.enable=1
          opcache.enable_cli=1
        tools: composer:v2
        coverage: none

      # if required node setup node
    - name: Setup Node
      if: inputs.node-version != ''
      uses: actions/setup-node@v2
      with:
        node-version: ${{ inputs.node-version }}

      # setup apache etc
    - name: prepare setup
      if: inputs.test-type != 'PluginTests'
      shell: bash
      run: /home/runner/work/appendix/scripts/bash/prepare.sh
      env:
        PHP_VERSION: ${{ inputs.php-version }}
        MATOMO_TEST_TARGET: ${{ inputs.test-type }}
        MYSQL_ADAPTER: ${{ inputs.mysql-driver }}
        ADDITION: ${{ inputs.addition }}

      # adding google woff
    - name: set up google woff
      if: inputs.test-command == 'IntegrationTestsCore'
      shell: bash
      run: |
        git clone --recursive https://github.com/google/woff2.git ../travis_woff2
        cd ../travis_woff2
        make clean all

      # setting up ldap for plugin
    - name: Setup ldap
      if: inputs.addition == 'ldap'
      shell: bash
      run: /home/runner/work/appendix/scripts/setup_ldap.sh

      # setting up plugin tests
    - name: PluginTests Test runing
      if: inputs.test-type == 'PluginTests'
      working-directory: /home/runner/work/matomo/matomo
      shell: bash
      run: /home/runner/work/appendix/scripts/bash/plugins/pluginTests.sh
      env:
        TEST_SUITE: ${{ inputs.test-type }}
        PLUGIN_NAME: ${{ inputs.plugin-name }}

      # running php or integration tests
    - name: Test running
      if: inputs.test-type == 'PHP'
      shell: bash
      run: |
        ./vendor/phpunit/phpunit/phpunit --configuration ./tests/PHPUnit/phpunit.xml --testsuite ${{ inputs.test-command }}
      env:
        TRAVIS: true
        GITHUB: true
        PHP_VERSION: ${{ inputs.php-version }}
        MYSQL_ADAPTER: ${{ inputs.mysql-driver }}

      # system checks failed, upload expected xml and PDF
    - name: upload artfact
      if: failure() && inputs.test-type == 'PHP'
      uses: actions/upload-artifact@v3
      with:
        name: ${{ inputs.run_id }}
        path: |
          /home/runner/work/matomo/matomo/plugins/**/tests/System/processed/**

    - name: download artface
      if: failure() && inputs.test-type == 'PHP'
      uses: actions/download-artifact@v3
      with:
        name: ${{ inputs.run_id }}
        path: |
          /home/runner/work/matomo/matomo/plugins/**/tests/System/processed/**


    - name: UI tests Group ${{ matrix.parts }}
      if: inputs.test-type == 'UI'
      shell: bash
      env:
        GITHUB: true
      run: |
        ./console tests:run-ui --store-in-ui-tests-repo --persist-fixture-data --assume-artifacts --core --extra-options="--num-test-groups=8 --test-group=${{ inputs.test-command }}"

    - name: upload processed screenshots
      if: failure() && inputs.test-type == 'UI'
      shell: bash
      run: /home/runner/work/appendix/scripts/bash/upload_artifacts.sh
      env:
        ARTIFACTS_PASS: ${{ inputs.artifect_pass }}
        GITHUB_REPO: ${{ inputs.repository }}
        GITHUB_BRANCH: ${{ inputs.ref }}
        GITHUB_RUN_ID: ${{ inputs.run_id }}
        GITHUB_RUN_NUMBER: ${{ inputs.run_number }}

    - name: View UI failures
      if: failure() && inputs.test-type == 'UI'
      shell: bash
      run: /home/runner/work/appendix/scripts/bash/view_ui_failed.sh
      env:
        GITHUB_REPO: ${{ inputs.repository }}
        GITHUB_BRANCH: ${{ inputs.ref }}
        GITHUB_RUN_ID: ${{ inputs.run_id }}

    - name: Running angularjs && vue tests
      if: inputs.test-type == 'Angular'
      shell: bash
      working-directory: ./tests/angularjs
      run: |
        npm install
        ./node_modules/karma/bin/karma start karma.conf.js --browsers ChromeHeadless --single-run

    - name: Javascript Tests
      if: inputs.test-type == 'JS'
      shell: bash
      run: |
        ./console tests:run-js --matomo-url='http://localhost'