name: 'Matomo Plugin Tests'
description: 'Running Matomo Tests'
inputs:
  git-head:
    description: "head"
    required: true
  git-sha:
    description: "sha"
    required: true
  plugin-name:
    description: "name"
    required: true
  test-type:
    description: 'test type'
    required: true
  php-version:
    description: '7.2-8.1'
    required: true
    default: '7.2'
  node-version:
    description: 'node version default 12'
    required: false
    default: '12'
  addition:
    description: 'additional test or setup'
    required: false
  secrets:
    description: ''
    required: false

runs:
  using: "composite"
  steps:
    - name: Checkout code
      shell: bash
      run: |
        cd /home/runner/work/
        git clone https://github.com/matomo-org/github-action-tests.git appendix

    - name: Checkout code
      uses: actions/checkout@v2
      with:
        repository: matomo-org/matomo
        path: ./matomo

    - name: Move File to right place
      shell: bash
      run: |
        mkdir /home/runner/work/matomo
        mv ./matomo /home/runner/work/matomo/
        ls -l /home/runner/work/appendix

    - name: Checkout Submodule to current Pull request
      shell: bash
      working-directory: /home/runner/work/matomo/matomo
      run: |
        cd plugins/${{ inputs.plugin-name }}
        git submodule update --init -- .
        git fetch origin ${{ inputs.git-head }}
        git checkout ${{ inputs.git-sha }}

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ inputs.php-version }}
        extensions: bcmath, ldap, curl, zip, pdo_mysql, mysqli, gd, redis
        ini-values: |
          memory_limit = 4024M,
          max_execution_time=10000,
          always_populate_raw_post_data=-1,
          error_reporting=E_ALL,
          log_errors=on, display_errors=on,
          allow_url_fopen = on,
          zend.exception_ignore_args = Off
          mysqli.allow_local_infile = On
        tools: composer:v2
        coverage: none

    - name: Setup Node
      if: ${{ inputs.test-type }} == 'UI'
      uses: actions/setup-node@v2
      with:
        node-version: ${{ inputs.node-version }}

    - name: prepare setup
      shell: bash
      run: /home/runner/work/appendix/scripts/bash/prepare.sh
      env:
        PHP_VERSION: ${{ inputs.php-version }}
        MATOMO_TEST_TARGET: ${{ inputs.test-type }}
        MYSQL_ADAPTER: 'PDO_MYSQL'

    - name: Setup ldap
      if: ${{ inputs.addition }} == 'ldap'
      shell: bash
      run: /home/runner/work/appendix/scripts/bash/setup_ldap.sh

    - name: PluginTests Test runing
      working-directory: /home/runner/work/matomo/matomo
      shell: bash
      run: /home/runner/work/appendix/scripts/bash/plugins/pluginTests.sh
      env:
        TEST_SUITE: ${{ inputs.test-type }}
        PLUGIN_NAME: ${{ inputs.plugin-name }}
